### ISSUE TITLE
Death penalty reduction sometimes gives you too much XP

### ISSUE THREAD

**Issue by ghost** [tonylukasavage/cv2r#101]

**Comment by BloodSweatAndCode** [comment]
reeland1787Today at 8:28 PM
You need at least 200 hearts at a game over
 
BurbToday at 8:29 PM
I think I've seen it with less
 
freeland1787Today at 8:29 PM
Smallest number I've seen is 202
In regards to the ferry boat, if we can't fix the sprite we can always joke that that's what happens when the boat is afflicted by the curse.
It won't affect game play much at all since the long jump mechanic still works off the messed up sprite.

**Comment by tonylukasavage** [comment]
fixed in 74bc6ff83e52c35913f7d11e47c1f060be661635
