### ISSUE TITLE
GAME START screen crashes after a few seconds on bizhawk

### ISSUE THREAD

**Issue by ghost** [tonylukasavage/cv2r#108]
Reported by spriven:

> i stepped away from a moment but put it on the start screen...and apparently it locked up and made this screeching noise.
i couldn't get it to do anything.
i reset the emu and the seed played fine. no issues
just weird on that start screen for some reason
was playing on bizhawk 2.3.1
the seed played fine though
no issues
just that start screen

https://clips.twitch.tv/VainAgileWalletKlappa

To be clear, this error does NOT occur on fceux, mesen, or console.

**Comment by BloodSweatAndCode** [comment]
This bug is different on bizhawk depending which NES core you use. If using `QuickNes` you get the error that spriven described. If you switch to `NesHawk` the sprites on the game start screen still glitch out, but the game does not crash.

**Comment by tonylukasavage** [comment]
It would spend way too much of my time chasing emulator-specific bugs that would likely require fixes in bizhawk rather than cv2r. I added a specific known issue to the top of the README (https://github.com/tonylukasavage/cv2r#platforms-with-known-issues) and unless someone wants to tackle this one, I'm going to consider that good enough for now. Happy to re-open this if someone proposes a fix though.
